// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI8NOFVEbKDiIwcNsASloudH6mW8rgXXQ',
    appId: '1:330926302773:web:3414c4ff2c19d8f4b7737c',
    messagingSenderId: '330926302773',
    projectId: 'arrowhead-5f658',
    authDomain: 'arrowhead-5f658.firebaseapp.com',
    storageBucket: 'arrowhead-5f658.appspot.com',
    measurementId: 'G-Z1WJ9Q8PJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbLg14lCw0Mrh19H2eMfjV_TLWrKopF0w',
    appId: '1:330926302773:android:399fcbfa761c21fbb7737c',
    messagingSenderId: '330926302773',
    projectId: 'arrowhead-5f658',
    storageBucket: 'arrowhead-5f658.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVcR4y4xJ8pnnK3cHGSK92Vwtmr_dq-5s',
    appId: '1:330926302773:ios:cd8aa85846729833b7737c',
    messagingSenderId: '330926302773',
    projectId: 'arrowhead-5f658',
    storageBucket: 'arrowhead-5f658.appspot.com',
    iosClientId: '330926302773-a8g38n4m6sbdncs6a2ciie91lg6kg8lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.arrowhead',
  );
}
